### ISSUE TITLE
WCS axis flipping. Causing difference image to be misaligned.

### ISSUE THREAD

**Issue by laldoroty** [laldoroty/phrosty#8]
Only happens with coadded template image. In Python, result is: 
![image](https://github.com/user-attachments/assets/c5c45513-c194-4de6-a20b-40c82f78a07c)

Aligned science image is:
![image](https://github.com/user-attachments/assets/969dd12b-8004-4a76-a248-764ae0f0b41a)
Coadd 4k cutout is:
![image](https://github.com/user-attachments/assets/d07b07ec-d267-4879-8d45-6b755576e605)

Looks like they were just slapped on top of each other and subtracted. However, DS9 seems to understand the alignment (left to right: coadd, coadd 4k cutout, convolved aligned science image, sky subtracted unaligned science image, sky subtracted "main" reference image (i.e., the WCS is from this individual image)):
![aligned](https://github.com/user-attachments/assets/b43a3e7e-e050-4104-8c63-2f0655e9ebfa)

**Comment by laldoroty** [comment]
Also, note that in Python, the images look mirrored. In DS9, the axes display as follows (in same order as above DS9 screenshot): 
![image](https://github.com/user-attachments/assets/584392cc-d6d8-43be-a80f-fc02689ae275)
![image](https://github.com/user-attachments/assets/d2f8205c-b5dd-499d-9170-f2caa7fdbfd7)
![image](https://github.com/user-attachments/assets/c3a451f3-8f63-4e96-b69a-2be507c9db0a)
![image](https://github.com/user-attachments/assets/f6846bf0-b329-4b3c-ae82-fbbebcce3611)
![image](https://github.com/user-attachments/assets/0d4cab12-81c8-4891-bcac-6e3e5afa43d9)

**Comment by laldoroty** [comment]
Currently, in code, I imalign the science image to the coadded image, not the single reference image with the WCS. Will try this. Changing these lines so coadd_img_path is skysub_ref_init[0] instead:

`        # Get science image PSF and rotate it according to the coadded reference. 
        sci_imsim_psf = get_imsim_psf(RA,DEC,band,pointing,sca,
                                     ref_path=coadd_img_path)
        sci_psf_path = rotate_psf(RA,DEC,sci_skysub_path,sci_imalign_path,
                                  band,pointing,sca,ref_path=coadd_img_path)`

The following line is already like this, but it didn't work yesterday...
`sci_imalign_path = imalign(skysub_ref_init[0],sci_skysub_path)`

**Comment by laldoroty** [comment]
Same results. Going to change everywhere I align to skysub_ref_init[0] to align to coadd_img_path.

**Comment by laldoroty** [comment]
Hit an array size error, need to use the 4k coadd cutout instead of the full coadd for aligning.

**Comment by laldoroty** [comment]
Coadd cutout isn't made until after all the aligning happens, so next time I do this I should try to move that particular part of the code earlier, if I can.

**Comment by laldoroty** [comment]
New science image and reference image after doing the above:
![image](https://github.com/user-attachments/assets/9acc8941-8042-4933-9c02-0973966875ed)
![image](https://github.com/user-attachments/assets/6f38e585-7d2c-408d-9a2e-5d2f81111ade)

Looks aligned to me! The final differenced and decorrelated image is: 
![image](https://github.com/user-attachments/assets/dfe3af4f-4953-4650-ae87-3de73d6677e3)

**Comment by laldoroty** [comment]
Important note: I thought this would be an issue with phrosty, so I filed the bug here, but it was actually how I call the functions in phrosty. The associated issue in the correct repo is here: https://github.com/Roman-Supernova-PIT/diff-img/issues/9

**Comment by laldoroty** [comment]
Okay, so now the images look aligned as they do above, but the code crashes when I'm generating the decorrelation kernel. The difference image looks like this: 
![image](https://github.com/user-attachments/assets/15790b6f-c5f8-4fc1-a672-e5fa329ace3c)

Still has too many things in it... error message below. 

``DIFFERENCE IMAGE PATH
/work/lna18/imsub_out/subtract/difference/diff_conv_align_skysub_Roman_TDS_simple_model_R062_35083_8.fits
MeLOn CheckPoint: DeCorrelation Kernel with size [1055, 1055]
MeLOn CheckPoint: Tail-Truncation Lost-Weight [nan %] (Absolute Percentage Error) 
DECORR KERNEL PATH
/work/lna18/imsub_out/dcker/DCKer_conv_align_skysub_Roman_TDS_simple_model_R062_35083_8.fits
Traceback (most recent call last):
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 280, in <module>
    main(sys.argv)
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 277, in main
    sfft_and_animate(o_id,band)
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 213, in sfft_and_animate
    dcimg_path = decorr_img(diff, dcker_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/phrosty/phrosty/imagesubtraction.py", line 421, in decorr_img
    dcdiff = convolve_fft(img_data, DCKer, boundary='fill', \
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/nddata/decorators.py", line 261, in wrapper
    result = func(data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/convolution/convolve.py", line 751, in convolve_fft
    raise Exception(
Exception: The kernel can't be normalized, because its sum is close to zero. The sum of the given kernel is < 0.01. For a zero-sum kernel, set normalize_kernel=False or pass a custom normalization function to normalize_kernel.``

**Comment by laldoroty** [comment]
Looking at the decorrelation kernel... 
```
hdu = fits.open(dckerpath)
img = hdu[0].data
shape = img.shape[0]
print(np.unique(img))
print(shape)
```
prints ``[nan]`` and ``1055``. I'm pretty sure the kernel shouldn't contain only nans, and it should also be 2D...

**Comment by laldoroty** [comment]
I wondered if SFFT just didn't like the discontinuities in the sky background (and therefore PSF discontinuities...????) so I cut it down to a 1000x1000 cutout and redid the subtraction. We get this: 
![image](https://github.com/user-attachments/assets/fff94405-e16d-49bb-a197-d0c4113be68d)
so... still not great

**Comment by laldoroty** [comment]
Was accidentally coadding images that hadn't been background-subtracted. in `sfft_and_animate.py`, changed `coadd_img_path, coadd_img_paths_all = swarp_coadd_img(filepaths_ref,skysub_ref_init[0],f'{oid}_{band}_{refvisit}_{refsca}_coadd.fits')` to `coadd_img_path, coadd_img_paths_all = swarp_coadd_img(skysub_ref,skysub_ref_init[0],f'{oid}_{band}_{refvisit}_{refsca}_coadd.fits')`.

**Comment by laldoroty** [comment]
Reference PSF has a 26 pixel NaN border around it, where the science PSF doesn't... 
![image](https://github.com/user-attachments/assets/29a068f1-a1a4-445b-825c-053e1a70f511)
![image](https://github.com/user-attachments/assets/3d7c7131-9bfc-4ee9-88ce-a9c7015117fd)

**Comment by laldoroty** [comment]
Okay, I got it to a place where it does the subtractions on the images with the coadd. Frankly, I have zero idea why it's working now, because I did a bunch of things, undid it back to a point where it still failed, and now it's working. 

I do still get this error when coadding the template PSFs, but I don't know why SWarp is "failing". It seems to be working fine, I get a coadded PSF out that looks different from an individual PSF.
Coadded PSF: 
![image](https://github.com/user-attachments/assets/74f6e19f-bd29-447d-ad28-7f1aebbb6754)

Individual PSF:
![image](https://github.com/user-attachments/assets/311954f5-3520-4732-9716-65d92ea98194)

```
/hpc/group/cosmology/lna18/sfft/sfft/utils/pyAstroMatic/PYSWarp.py:330: UserWarning: MeLOn WARNING: SWarp FAILED on [['/work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_R062_6_17.fits', '/work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_R062_1928_10.fits', '/work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_R062_2314_6.fits', '/work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_R062_2319_8.fits', '/work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_R062_2709_7.fits']]!
  warnings.warn('MeLOn WARNING: %s' %_warn_message)
Template PSF succesfully coadded.
```

Here's the difference image and zoomed-in SN: 
![image](https://github.com/user-attachments/assets/864ac8c8-6a2d-490f-8c2f-2da294e6da5c)
![image](https://github.com/user-attachments/assets/ea4e1dd9-5076-44e0-b8b1-9c2dac6f313e)

**Comment by laldoroty** [comment]
Closing because the difference image is now aligned, but opening another issue because there is still an x-y orientation issue that pops up when we mk_lc.py.
